SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Entity/Image.php
<?php

namespace OC\PlatformeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="OC\PlatformeBundle\Repository\ImageRepository")
 * @ORM\HasLifeCycleCallbacks()
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    private $file;
    public function getFile(){
        return $this->file;
    }
    public function setFile(UploadedFile $file=null){
         $this->file=$file;
         if($this->url !==null){
             $this->tempFilename=$this->url;
             $this->url=null;
             $this->alt=null;
         }
    }


    private $tempFilename;
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload(){
        if(null === $this->file){
            return;
        }
        $this->url=$this->file->guessExtension();
        $this->alt=$this->file->getClientOriginalName();
    }


    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload(){
        if($this->file === null){
             return ;
        }
       if(null !== $this->tempFilename){
         $oldFile=$this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
         if(file_exists($oldFile)){
             unlink($oldFile);
         }
       }
       $this->file->move($this->getUploadRootDir(),'/'.$this->id.'.'.$this->url);

    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload(){
        $this->tempFilename=$this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
     * @ORM\PostRemove
     */
    public function removeUpload(){
        if(file_exists($this->tempFilename)){
            unlink($this->tempFilename);
        }
    }

    /**
     * CHEMIN RELATIF
     */
    public function getUploadDir(){
        return 'uploads/img';
    }

    /**
     * CHEMIN ABSOLU
     */
    protected function getUploadRootDir()
    {
        return '/var/www/html/Symfony/web/'.$this->getUploadDir();
    }

    public function getWebPath(){
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }
}

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Form/AdvertType.php
<?php

namespace OC\PlatformeBundle\Form;

use OC\PlatformeBundle\Repository\CategoryRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
class AdvertType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $pattern="%";
        $builder
            ->add('date',DateTimeType::class)
            ->add('title',TextType::class)
            ->add('content',TextareaType::class)
            ->add('published',CheckboxType::class,['required'=>false])

            // FORMULAIRE DE L'IMAGE
            ->add('image',ImageType::class)

            //FORMULAIRE DES CATEGORIES
            ->add('categories',EntityType::class,array(
                'class'=>'OCPlatformeBundle:Category',
                'choice_label'=>'name',
                'multiple'=>true,
                'query_builder'=>function(CategoryRepository $repository) use($pattern) {
                       return $repository->getLikeQueryBuilder($pattern);
               }
            ))
            //BOUTTON SUBMIT
            ->add('save',SubmitType::class,array(
                    'attr'=>array(
                        'class'=>'btn btn-block btn-primary'
                    )
                )
            );

           $builder->addEventListener(FormEvents::PRE_SET_DATA,function (FormEvent $event){
              $advert=$event->getData();
              if(null === $advert){
                return;
              }
              if(!$advert->getPublished() || null === $advert->getId()){
                  $event->getForm()->add('published',CheckboxType::class,['required'=>false]);
              }else{
                  $event->getForm()->remove('published');
              }
           });
    }/**
 * {@inheritdoc}
 */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'OC\PlatformeBundle\Entity\Advert'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'oc_platformebundle_advert';
    }


}

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Controller/AdvertController.php
<?php

namespace OC\PlatformeBundle\Controller;

use OC\PlatformeBundle\Form\ListAdvertsType;
use SoapClient;
use OC\PlatformeBundle\Antispam\OCAntispam;
use OC\PlatformeBundle\Beta\BetaHTMLAdder;
use OC\PlatformeBundle\Beta\BetaListener;
use OC\PlatformeBundle\Email\ApplicationMailer;
use OC\PlatformeBundle\Entity\Advert;
use OC\PlatformeBundle\Entity\Application;
use OC\PlatformeBundle\Event\MessagePostEvent;
use OC\PlatformeBundle\Event\PlatformEvents;
use OC\PlatformeBundle\Form\AdvertEditType;
use OC\PlatformeBundle\Form\AdvertType;
use Swift_Mailer;
use Symfony\Component\Finder\Exception\AccessDeniedException;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Validator\Constraints\DateTime;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class AdvertController extends Controller
{

    public function purgeAction($days)
    {


        return new  Response("");
    }

    public function indexAction($page)
    {
        if ($page < 1) {
            throw $this->createNotFoundException('page ' . $page . ' inexistante');
        }
        $nbPerPage = 3;
        $listAdverts = $this->getDoctrine()
            ->getManager()
            ->getRepository("OCPlatformeBundle:Advert")
            ->getAdverts($page, $nbPerPage);
        $nbPages = ceil(count($listAdverts) / $nbPerPage);
        if ($page > $nbPages) {
            throw $this->createNotFoundException("La page " . $page . " n'existe pas");
        }
        return $this->render('OCPlatformeBundle:Advert:index.html.twig', [
                'page' => $page,
                'listAdverts' => $listAdverts,
                'nbPages' => $nbPages
            ]
        );
    }

    public function viewAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository("OCPlatformeBundle:Advert");
        $advert = $repository->find($id);
        if ($advert === null) {
            throw new NotFoundHttpException("L'annonce d'id " . $id . "n'existe pas");
        }

        $listApplications = $em
            ->getRepository("OCPlatformeBundle:Application")
            ->findBy(['advert' => $advert]);

        $listAdvertSkills = $em
            ->getRepository("OCPlatformeBundle:AdvertSkill")
            ->findBy(['advert' => $advert]);

        return $this->render('OCPlatformeBundle:Advert:view.html.twig', [
                'advert' => $advert,
                'listeApplications' => $listApplications,
                'listAdvertSkill' => $listAdvertSkills
            ]
        );
    }
    //    /**
//     * @Security("has_role('ROLE_ADMIN')")
//     */
    public function addAction(Request $request)
    {
        if (!$this->get('security.authorization_checker')
            ->isGranted('ROLE_ADMIN')) {
            throw new AccessDeniedException("accés limité seulement à l'administrateur du site");
        }
        /**
         * RÉCUPERER L'UTILISATEUR COURANT
         */
        $token = $this->container->get('security.token_storage')->getToken();
        //$token=$this->get('security.token_storage')->getToken();
        $user = $token->getUser();
        $advert = new Advert();
        /**
         * RENSEIGNER L'UTILISATEUR CONNÉCTÉ DANS L'OBJET ADVERT
         */
        $advert->setUser($user);
        /**
         * PERMET DE PRE-REMPLIR LES CHAMPS DEPUIS L'OBJET $advert
         */
        $form = $this->createForm(AdvertType::class, $advert);
        // $form=$this->get('form.factory')->create(AdvertType::class,$advert);
        /**
         * TRAITEMENT DE LA REQUETE
         */

        if ($request->isMethod("POST")) {
            /*
             * PERMET D'AFFECTER LES VALEURS SOUMISES DU FORMULAIRE A L'OBJET $advert
             */
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                //$advert->getImage()->upload();

                /**
                 * CRÉATION ET DÉCLENCHEMENT DE L'EVENEMENT POST MESSAGE (MessagePostEvent)
                 */
                $event = new MessagePostEvent($advert->getContent(), $advert->getUser());
                $this->get('event_dispatcher')->dispatch(PlatformEvents::POST_MESSAGE, $event);
                $advert->setContent($event->getMessage());

                $em = $this->getDoctrine()->getManager();
                $em->persist($advert);
                $em->flush();
                $this->addFlash('success', 'Annonce ajoutée avec succés');
                return $this->redirectToRoute('oc_platform_home');
            } else {
                $validator = $this->get('validator');
                $listErrors = $validator->validate($advert);
                return $this->render("OCPlatformeBundle:Advert:add.html.twig", [
                        'form' => $form->createView(),
                        'listErrors' => $listErrors
                    ]
                );
            }
        }

        return $this->render("OCPlatformeBundle:Advert:add.html.twig", [
                'form' => $form->createView()
            ]
        );
    }

    public function editAction($id, Request $request)
    {
        /**
         * Récuperer l'annonce liée à l'id
         */
        // $title=$request->request->get("title");
        $em = $this->getDoctrine()->getManager();
        $advert = $em->getRepository("OCPlatformeBundle:Advert")->find($id);
        $form = $this->createForm(AdvertEditType::class, $advert);

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $em->flush();
                $this->addFlash('success', 'Annonce modifiée avec succés');
                return $this->RedirectToRoute('oc_platform_view', ['id' => $advert->getId()]);
            }
        }
        return $this->render('OCPlatformeBundle:Advert:edit.html.twig', [
                'form' => $form->createView(), 'advert' => $advert
            ]
        );
    }

    public function deleteAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $advert = $em->getRepository("OCPlatformeBundle:Advert")->find($id);
        if ($advert === null) {
            throw new NotFoundHttpException("L'annonce d'id " . $id . " n'existe pas");
        }
        $form = $this->get('form.factory')->create();
        if ($request->isMethod("POST")) {
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                /**
                 * SUPPRIMER LES APPLICATIONS LIÉES
                 * SI ON N'A PAS MIS cascade={"remove"} DANS L'ENTITÉ ADVERT
                 */
//                foreach ($advert->getApplications() as $application){
//                    $em->remove($application);
//                }
                /**
                 * SUPPRIMER L'ADVERT
                 */
                $em->remove($advert);
                $em->flush();
                $this->addFlash("success", "L'annonce a été supprimée avec succés");
                return $this->redirectToRoute('oc_platform_home');
            }
        }


        return $this->render("OCPlatformeBundle:Advert:delete.html.twig", [
                'form' => $form->createView(), 'advert' => $advert
            ]
        );

    }

    public function menuAction($limit)
    {
        /*
         * création des 3 dérniéres annonces
         */
        $em = $this->getDoctrine()->getManager();
        $repository = $em->getRepository("OCPlatformeBundle:Advert");
        $adverts = $repository->findBy(
            [],
            ['date' => 'DESC'],
            $limit,
            0
        );
        return $this->render("OCPlatformeBundle:Advert:menu.html.twig", ['adverts' => $adverts]);
    }

    public function showAction()
    {
//       $em=$this->getDoctrine();
//       $repository=$em->getRepository("OCPlatformeBundle:Advert");
//       $advert=$repository->find(3);
//        $advert=$this->getDoctrine()
//            ->getRepository("OCPlatformeBundle:Advert")
//            ->find(3);

//        $query=$repository->createQueryBuilder('a')
//            ->select('a')
//            ->getQuery();
//        $adverts=$query->getResult();
        $repository = $this->getDoctrine()->getRepository("OCPlatformeBundle:Advert");
        //$advert=$repository->myFindOne(7);
        $adverts = $repository->getAdvertWithCategories(['Développeur', 'Intégrateur']);

        return $this->render("OCPlatformeBundle:Advert:show.html.twig", ['adverts' => $adverts]);
    }

    public function testAction()
    {
//        $advert_id=2;
//        $limit=2;
//        $repository=$this->getDoctrine()->getRepository("OCPlatformeBundle:Application");
//        $advert=$repository->getApplicationsWithAdvert($limit,$advert_id);

        /**
         * La liste des candidatures pour une annonce donnée
         */

//        $em=$this->getDoctrine()->getManager();
//        $repository=$em->getRepository("OCPlatformeBundle:Advert");
//        $advert_id=5;
//        $advert=$repository->find($advert_id);
//        $applications=$em
//            ->getRepository("OCPlatformeBundle:Application")
//            ->findBy(['advert'=>$advert]);
//
//        $em=$this->getDoctrine()->getManager();
//        $advert=$em
//            ->getRepository("OCPlatformeBundle:Advert")
//            ->find(42);
//        $applications=$advert->getApplications();
//        foreach ($applications as $app){
//            dump($app);

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Resources/views/Advert/add.html.twig
{% extends "OCPlatformeBundle::layout.html.twig" %}
{% block title %}
    L'ajout d'une annonce - {{ parent() }}
{% endblock %}
{% block body %}
    <h3>Formulaire d'ajout d'une annonce</h3>

    {% if listErrors is defined %}
        {% if listErrors|length > 0 %}
            {% for error in listErrors %}
               <div class="alert alert-danger"> {{ error.message }}</div>
            {% endfor  %}
        {% endif %}
    {% endif %}

    <div class="well">
        {{ form_start(form,{'attr':{'class':'form-'}}) }}
        {{ form_errors(form) }}
        {{ form_widget(form) }}
        {{ form_rest(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Resources/views/Advert/applications_by_advert.html.twig
{% if applications is not empty %}
    <h4 class="alert alert-info">Voici les candidatures qui correspondent à l'annonce choisie</h4>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>L'Auteur</th>
            <th>Le Contenu</th>
            <th>La Date</th>
        </tr>
        </thead>
        <tbody>
        {% for app in applications %}
            <tr>
                <td>{{ app.author }}</td>
                <td>{{ app.content }}</td>
                <td>{{ app.date|date("d/M/Y") }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <h4 class="alert alert-warning  ">il n'y pas encore de candidatures pour cette annonce ! </h4>
{% endif %}

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Resources/views/Advert/delete.html.twig
{% extends "OCPlatformeBundle::layout.html.twig" %}
{% block title %}
    Supprimer une annonce - {{ parent() }}
{% endblock %}
{% block body %}
<h2>Supprimer une annonce</h2>
    <p>
        Etes-vous sûr de vouloir supprimer l'annonce {{ advert.title }} ?
    </p>
    <form action="{{ path('oc_platform_delete',{'id':advert.id}) }}" method="post">
        <a href="{{ path('oc_platform_view',{'id':advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à l'annonce
        </a>
        <button type="submit" class="btn btn-danger">Supprimer</button>
        {{ form_rest(form) }}
    </form>
{% endblock %}

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Resources/views/Advert/edit.html.twig
{% extends "OCPlatformeBundle::layout.html.twig" %}
{% block title %}
    Modifier une annonce - {{ parent() }}
{% endblock %}
{% block body %}
    <h2>Modifier une annonce</h2>
    {{ include("OCPlatformeBundle:Advert:form.html.twig",{'var':'value'}) }}
    <p>
        Vous éditez une annonce déja existante,merci de ne pas changer l'esprit général de l'annonce déja publiée
    </p>
    <p>
        <a href="{{ path('oc_platform_view',{'id':advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à la liste
        </a>
    </p>
{% endblock %}

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Resources/views/Advert/form.html.twig
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_rest(form) }}
    {{ form_end(form) }}

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Resources/views/Advert/index.html.twig
{% extends "OCPlatformeBundle::layout.html.twig" %}
 {% block title %} {{ parent() }} - Index {% endblock %}
{% block body %}
    {% for advert in listAdverts %}
        <h3>{{ advert.title }}</h3>
        <hr>
    {% endfor %}
    {#PAGINATION#}
    {% include 'OCPlatformeBundle:Advert:index_pagination.html.twig' with {'page':page,'nbPages':nbPages} only %}
{% endblock %}

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Resources/views/Advert/index_pagination.html.twig
<style>
    .pagination{
        position: fixed;
        bottom:200px;
    }
    .link-disabled {
        cursor: default;
        pointer-events: none;
    }
</style>
<ul class="pagination">
    <li>
        <a href="{{ path('oc_platform_home',{'page':(page-1)}) }}" {% if page==1 %} class="link-disabled" {% endif %} >
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% for p in range(1,nbPages) %}
        <li {% if p==page %} class="active" {% endif %}>
            <a href="{{ path('oc_platform_home',{'page':p}) }}">
                {{ p }}
            </a>
        </li>
    {% endfor %}
    <li>
        <a href="{{ path('oc_platform_home',{'page':(page+1)}) }}"
           {% if page==nbPages %} class="link-disabled" {% endif %} >
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
</ul>

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Resources/views/Advert/list_adverts.html.twig
{% extends "OCPlatformeBundle::layout.html.twig" %}
{% block title %} Candidatures par annonce - {{ parent() }} {% endblock %}
{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_rest(form) }}
    {{ form_end(form) }}
    <div id="show"></div>
    <script>
        $(document).ready(function () {
            var listAdverts = $('#list_adverts_Annonces');
            var show = $("#show");
            listAdverts.change(function () {
                show.html('');
                var index = $("#list_adverts_Annonces option:selected").index();
                if (index > 0) {
                    $.ajax({
                        url: "{{ path('oc_platform_advert_applications') }}",
                        type: "POST",
                        data: {
                            // value: listAdverts.text()
                            advert_id: listAdverts.val()
                        },
                        success: function (rendered_twig) {
                            show.html(rendered_twig);
                        }
                    });
                }
            });
        });
    </script>
{% endblock %}

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Resources/views/Advert/menu.html.twig
<ul class="nav nav-pills nav-stacked">
    {% for advert in adverts %}
    <li>
        <a href="{{ path('oc_platform_view',{'id':advert.id,'title':advert.title}) }}">{{ advert.title }}</a>
    </li>
    {% endfor %}
</ul>

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Resources/views/Advert/show.html.twig
{#{{ checkIfSpam('123') }}#}
{{ dump(adverts) }}

SYMFONY/openclassroom_V_3.2/src/OC/PlatformeBundle/Resources/views/Advert/view.html.twig
{% extends "OCPlatformeBundle::layout.html.twig" %}
{% block title %}
    Lecture d'une annonce - {{ parent() }}
{% endblock %}
{% block body %}
    {% if advert.image is not null %}
        <img src="{{ asset(advert.image.webPath)}}"
             alt="{{ advert.image.alt }}">
    {% endif %}
    <h1>{{ advert.title }}</h1>
    <h3>par {{ advert.author }} le {{ advert.date|date("d/m/Y") }}</h3>
    <p>
        <a href="{{ path('oc_platform_home') }}" class="btn btn-default">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour à la liste
        </a>
        <a href="{{ path('oc_platform_edit',{'id':advert.id}) }}" class="btn btn-default">
            <i class="glyphicon glyphicon-edit"></i>
            Modifier l'annonce
        </a>
        <a href="{{ path('oc_platform_delete',{'id':advert.id}) }}" class="btn btn-danger">
            <i class="glyphicon glyphicon-trash"></i>
            Supprimer cette annonce
        </a>
    </p>
{% endblock %}